name: "Build and push images"

on:
  workflow_dispatch:

jobs:
  Building:
      runs-on: ubuntu-latest
      name: "Build wx images"
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        DOCKERHUB_REPOSITORY: ${{ secrets.DOCKER_HUB_USERNAME }}/wxx:latest

      steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0

      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Build and push images to Docker hub
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ env.DOCKERHUB_REPOSITORY }}
